# Generated by Django 5.1.5 on 2025-01-23 10:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trantrac", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={
                "verbose_name": "conto bancario",
                "verbose_name_plural": "conti bancari",
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "categoria", "verbose_name_plural": "categorie"},
        ),
    ]
