# Generated by Django 5.1.5 on 2025-01-29 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trantrac", "0002_alter_account_options_alter_category_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subcategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trantrac.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "sottocategoria",
                "verbose_name_plural": "sottocategorie",
            },
        ),
    ]
