# Generated by Django 5.1.5 on 2025-01-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trantrac", "0003_subcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="subcategory",
            name="skip_sheet_save",
            field=models.BooleanField(default=False),
        ),
    ]
